-- Create collections table with all required fields
CREATE TABLE IF NOT EXISTS `collections` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `imagekit_file_id` varchar(255) DEFAULT NULL,
  `imagekit_url` varchar(255) DEFAULT NULL,
  `imagekit_thumbnail_url` varchar(255) DEFAULT NULL,
  `imagekit_file_path` varchar(255) DEFAULT NULL,
  `image_size` int(11) DEFAULT NULL,
  `original_image_size` int(11) DEFAULT NULL,
  `image_width` int(11) DEFAULT NULL,
  `image_height` int(11) DEFAULT NULL,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `show_in_homepage` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `collections_is_active_index` (`is_active`),
  KEY `collections_sort_order_index` (`sort_order`),
  KEY `collections_slug_index` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
